### ISSUE TITLE
Update liquidity script for new command formats

### ISSUE THREAD

**Issue by peterbarrow** [vegaprotocol/sample-api-scripts#119]
The old liquidity command was used for creating, amending and cancelling a liquidity provision. That has changed now as we have a separate command for each action. This ticket is to update the existing scripts to only create a new LP and to add 2 more sets of scripts for performing amending and cancelling.

**Comment by candida-d** [comment]
Since pegged orders are undergoing similar changes, this would be a good issue/PR to also incorporate those changes (as discussed with @peterbarrow)

**Comment by candida-d** [comment]
Since pegged orders are undergoing similar changes, this would be a good issue/PR to also incorporate those changes (as discussed with @peterbarrow)
