### ISSUE TITLE
Create an example json payload for providing Oracle source

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/sample-api-scripts#122]
In order to make providing an Oracle source easy we need a sample script / json payload to be able to use the documentation in:

https://docs.vega.xyz/protodocs/vega/commands/v1/oracles.proto/#oracledatasubmissionoraclesource

- https://github.com/vegaprotocol/specs-internal/issues/541

**Comment by JonRay15** [comment]
Is this scheduled yet @gordsport ?

**Comment by gordsport** [comment]
> Is this scheduled yet @gordsport ?

Currently set for consideration for the next Sprint and before enable trading

**Comment by peterbarrow** [comment]
It looks like this ticket isn't valid anymore because we cannot enter an oracle source other than via a market proposal (I checked with Valentin). Are you OK to close this @gordsport ?

**Comment by gordsport** [comment]
From todays x-function meeting we said before closing this we need to check and see if we have scripts for providing an oracle source to settle a market?

@cdm please can you run @peterbarrow through what we have for the incentives and what may still be required?

**Comment by wwestgarth** [comment]
Possibly helpful, and maybe relevant: I have a branch from a while when I was messing around with vega that added oracle submission to terminate/settle a market: https://github.com/vegaprotocol/sample-api-scripts/compare/oracle-submission

Might be able to reuse some of it.

**Comment by gordsport** [comment]
no longer required, we don't support adding an oracle source by itself, only as part of the market proposal.
