### ISSUE TITLE
Sample API script remediation

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/sample-api-scripts#123]
Make sure that
- [ ] All the scripts in the repo "work" in the sense they at least run without failing and produce the action they advertise
- [ ] This is added to CI pipeline on `vega` so that we don't end up with this massive regression again
- [ ] Lot of them apparently use outdated mode of interaction with the `vegawallet` and thus can be simplified. 
- [ ] Update documentation to reflect changes that have been made. 
- [ ] Revisit whether we want `source credentials` be the way config is set for Python scripts; to me it would seem better to have a Python config file that the scripts then import (so after editing config I don't have to run another command). 
- [ ] Add this repo to the release process and *tag* so that users can always find a flawless version for the version of vega they wish to interact with.

**Comment by edd** [comment]
In the related discussion, @davidsiska-vega mentioned that to him shell scripts could just go in the bin.

I disagree. They're much less important than the code-that-could-be-built-on, but they're the way I'd prefer to play around with a network at first. So, accepting that they're lower priority:

https://docs.vega.xyz/docs/tools/vega-wallet/cli-wallet/latest/guides/build-send-commands/#build-commands was introduced after the original shell scripts were written. I propose that we rewrite them using that functionality to massively simplify the scripts, as a separate ticket, after the code is done. 

This has the upside that the shapes of generated transactions won't change unexpectedly - as long as the shape going *in* to the wallet doesn't change, and that's testable in CI.

**Comment by cdm** [comment]
Closed, superceded by work in #163
