### ISSUE TITLE
Remove Python GRPC examples

### ISSUE THREAD

**Issue by edd** [vegaprotocol/sample-api-scripts#142]
The Pythoin GRPC samples rely on a Python module that has [not been updated](https://github.com/vegaprotocol/api), and is not scheduled to be updated again any time soon. They will no longer be embedded in the docs, and they won't work, so let's remove em

**Comment by cdm** [comment]
Closed, superceded by work in #163

**Comment by cdm** [comment]
Plan currently for GRPC will be supported in a future work task by @SuDa2103 in python once we've worked out where the protoc generated python client will live and who will support it
