### ISSUE TITLE
Create market script is missing postionDecimalPlaces

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/sample-api-scripts#143]
This function should be added to the sample-api scripts when creating a market so that it can offer decimal points to position sizes.
Not yet on docs.fairground.wtf but on https://docs.vega.xyz/docs/testnet/tutorials/proposals/new-market-proposal

Tried it on fairground by adding it to the existing creation of market scripts and the proposed market worked,

"newMarket": {
"changes": {
"positionDecimalPlaces": 5,
"instrument": {

**Comment by cdm** [comment]
Closed, superceded by work in #163
