### ISSUE TITLE
Remove sample scripts that are not listed in this ticket

### ISSUE THREAD

**Issue by edd** [vegaprotocol/sample-api-scripts#158]
https://github.com/vegaprotocol/documentation/issues/184#issue-1333513404

- #144
- #145
- #146 
- #147 
- #148 
- #149 
- #150 
- #151
- #152 
- #153 
- #154
- #155 
- #156 
- #157 

This is based on the assumption that as part of any of the above tickets, ones that are so broken as to no longer be useful have been deleted.

**Comment by cdm** [comment]
All now completed an merged to master
