### ISSUE TITLE
Event streaming bash script not working for me

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/sample-api-scripts#22]
I'm getting the following error when trying to run the stream-events shell script in Gitpod. Is here the correct place to raise it? :-)

<img width="747" alt="image" src="https://user-images.githubusercontent.com/16691275/95005919-e5797200-05f5-11eb-9154-ccd1e5c8ea20.png">

**Comment by ashleyvega** [comment]
@tamlyn10 `bash stream-events/stream-events.sh` now works.
