### ISSUE TITLE
Update credentials to support fish shell

### ISSUE THREAD

**Issue by edd** [vegaprotocol/sample-api-scripts#48]
`source credentials` does not work in [fish](http://fishshell.com):

```
credentials (line 4): Unsupported use of '='. In fish, please use 'set WALLET_NAME "edd"'.
from sourcing file credentials
source: Error while reading file “credentials”
```
By switching the credentials.template over to use the format `set VAR "value"` we support both bash and fish, while currently we only support bash*.

~~* the inferior shell~~

**Comment by cdm** [comment]
Thanks for the 🐛 report, I'll spin off a branch and get you to test this for us if you're happy to be my test subject 🙏

**Comment by cdm** [comment]
Just testing this in zsh and I'm not sure it works as you suggest, I'll search for a xplat solution, fallback I'll add a section on this to troubleshooting

**Comment by cdm** [comment]
A possible solution is something like [this](https://stackoverflow.com/a/47902450), but then that's maybe harder to deal with for newbie users. Since I dont have fish, please can you review/test the best solution?

**Comment by edd** [comment]
Fish is the least common of three I suspect, so let’s just leave it and awkward people like me can figure it out for themselves
