### ISSUE TITLE
Pegged order not returning rejected status

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/sample-api-scripts#57]
I just tried to do a pegged order using the sample API scripts and Gitpod. I used a Vega wallet in the credentials, that didn't have any collateral. I would expect this to return "rejected" but the code just kept waiting.. (see screenshot). I eventually ended it by doing ctrl c.

<img width="1852" alt="image" src="https://user-images.githubusercontent.com/16691275/107414936-9a72ec80-6b0a-11eb-81d3-df0fc4811959.png">

**Comment by cdm** [comment]
Thanks, if you have no collateral, the core will give a rejection for this (margin_check_failed). I can check and improve, were you on testnet?

**Comment by jeremyletang** [comment]
Well, if you don’t have any kind of asset deposited on vega, the transaction will be rejected on the tendermint pool, and will not even reach the core, at which point it could eventually be rejected.

I would guess your script is waiting for the order to come from the event bus which will never happen?

**Comment by cdm** [comment]
Im investigating, will confirm what's going on and update ticket

**Comment by cdm** [comment]
I can replicate this (for pub key with no assets), the signed pegged order is prepared, signed and sent successfully via the wallet service. At which point it disappears, or more accurately it does not show up when polling the orderByReference endpoint.

**Comment by cdm** [comment]
Need to switch the wallet server to use sync transaction mode when sending in to tendermint for rejection reason of kind "No assets found for pubkey", rejection reasons that are set by the core will be returned. Same as #58

**Comment by cdm** [comment]
Easy fix - change samples to use:

s.POST("/api/v1/messages/sync", ExtractToken(s.SignTxSync))

**Comment by cdm** [comment]
Fixed in https://github.com/vegaprotocol/sample-api-scripts/pull/72
