### ISSUE TITLE
Adding "rejection reasons" to orders

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/sample-api-scripts#58]
It would be great to see why an order has been rejected and at the moment I think we don't return that. I noticed that in the pegged orders script, but I seem to recall at the Testnet Jam we also had this occur for placing a normal order.

**Comment by cdm** [comment]
Need to switch the wallet server to use `sync` transaction mode when sending in to tendermint for rejection reason of kind "No assets found for pubkey", rejection reasons that are set by the core will be returned.

**Comment by cdm** [comment]
Will investigate this and add any improvements as part of #57 (switch to SYNC transaction message submit)

**Comment by cdm** [comment]
Rejection reasons added to samples in PR https://github.com/vegaprotocol/sample-api-scripts/pull/72
