### ISSUE TITLE
submit-amend-cancel-orders should show order version

### ISSUE THREAD

**Issue by edd** [vegaprotocol/sample-api-scripts#70]
https://github.com/vegaprotocol/sample-api-scripts/blob/30032c9f59b49dddca4431a7aa6a1a6af07c48ba/submit-amend-cancel-orders/submit-amend-cancel-orders.py#L216-L218

While trying this script out (see #69  / #68) we were trying to work out if the amend had succeeded. The output is there, but I was looking for the order version field to see that the details output by the lines above were the updated values, like it says it is. 

A useful field for this is the (relatively) new version field which gets incremented on user amends. Adding it in this debug output would be cool

**Comment by cdm** [comment]
Completed in https://github.com/vegaprotocol/sample-api-scripts/pull/72
