### ISSUE TITLE
Write some new go scripts

### ISSUE THREAD

**Issue by edd** [vegaprotocol/sample-api-scripts#88]
In the distant past (read: recently), there was an API dance for REST/GraphQL clients that involved:

- Using a `prepareX` command on a node
- Taking an unsigned message from the response
- Sending that response to a wallet server to forward to a node via GRPC

This is now gone, and instead it's possible to use [vegaprotocol/go-wallet](https://github.com/vegaprotocol/go-wallet) to prepare and submit the transaction in one call. It would be great to check over the existing scripts to see if this pattern could be used to reduce the steps involved, or if some are using the now removed `prepareX` endpoints.

Related: https://github.com/vegaprotocol/go-wallet/issues/245

# Tasks
- [ ] Audit sample api scripts for prepare calls
- [ ] Check to see if the `commands` subcommand could neaten any scripts

**Comment by wwestgarth** [comment]
#96 outright removed the golang examples, so this ticket is now more of a "write some new go examples"
